### ISSUE TITLE
Pam's Harvestcraft 1.7.10Lb 

### ISSUE THREAD

**Issue by Ashakiwi** [Tonius/NEI-Integration#106]
Crashes when viewing any recipe in Survival mode. Tried the fix for La and it crashed on loading NEI. 

Crash Report:
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/20/16 9:11 PM
Description: Updating screen events

java.lang.NoSuchMethodError: com.pam.harvestcraft.PresserRecipes.smelting()Lcom/pam/harvestcraft/PresserRecipes;
    at tonius.neiintegration.mods.harvestcraft.RecipeHandlerPresser.loadCraftingRecipes(RecipeHandlerPresser.java:91)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
    at tonius.neiintegration.RecipeHandlerBase.loadCraftingRecipes(RecipeHandlerBase.java:100)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
    at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
    at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
    at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at tonius.neiintegration.mods.harvestcraft.RecipeHandlerPresser.loadCraftingRecipes(RecipeHandlerPresser.java:91)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
    at tonius.neiintegration.RecipeHandlerBase.loadCraftingRecipes(RecipeHandlerBase.java:100)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
    at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
    at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
    at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['theraisama'/222, l='MpServer', x=-139.20, y=100.62, z=-143.00]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-193,64,114), Chunk: (at 15,4,2 in -13,7; contains blocks -208,0,112 to -193,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 162447 game time, 1163 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 162 total; [EntityBat['Bat'/256, l='MpServer', x=-94.27, y=46.67, z=-94.60], EntityPig['Pig'/257, l='MpServer', x=-103.16, y=98.00, z=-100.78], EntityZombie['Zombie'/258, l='MpServer', x=-187.13, y=27.00, z=-129.25], EntityClientPlayerMP['theraisama'/222, l='MpServer', x=-139.20, y=100.62, z=-143.00], EntityCreeper['Creeper'/259, l='MpServer', x=-130.50, y=17.00, z=-177.50], EntityCreeper['Creeper'/260, l='MpServer', x=-131.50, y=17.00, z=-176.50], EntityPig['Pig'/261, l='MpServer', x=-134.94, y=101.00, z=-185.06], EntitySheep['Sheep'/262, l='MpServer', x=-130.63, y=101.00, z=-177.81], EntityZombie['Zombie'/263, l='MpServer', x=-88.50, y=11.00, z=-134.50], EntityPig['Pig'/264, l='MpServer', x=-81.91, y=120.00, z=-138.94], EntityItem['item.name.lootbags_lootbagBat'/265, l='MpServer', x=-137.38, y=32.13, z=-95.03], EntitySkeleton['Skeleton'/266, l='MpServer', x=-184.50, y=27.00, z=-127.50], EntityChicken['Chicken'/267, l='MpServer', x=-179.56, y=62.33, z=-119.59], EntityCreeper['Creeper'/268, l='MpServer', x=-125.59, y=13.00, z=-178.00], EntityCreeper['Creeper'/269, l='MpServer', x=-90.41, y=31.00, z=-122.00], EntityBat['Bat'/270, l='MpServer', x=-77.68, y=28.85, z=-115.96], EntityZombie['Zombie'/271, l='MpServer', x=-88.97, y=45.00, z=-109.50], EntitySheep['Sheep'/272, l='MpServer', x=-91.81, y=111.00, z=-118.13], EntityPig['Pig'/273, l='MpServer', x=-112.31, y=97.00, z=-92.50], EntityPig['Pig'/274, l='MpServer', x=-197.03, y=65.00, z=-174.13], EntityPig['Pig'/275, l='MpServer', x=-193.13, y=66.00, z=-179.97], EntityPig['Pig'/276, l='MpServer', x=-186.88, y=64.00, z=-160.81], EntityChicken['Chicken'/277, l='MpServer', x=-177.53, y=65.00, z=-172.41], EntitySkeleton['Skeleton'/280, l='MpServer', x=-162.56, y=12.00, z=-185.31], EntityCreeper['Creeper'/281, l='MpServer', x=-173.50, y=44.00, z=-182.50], EntitySheep['Sheep'/282, l='MpServer', x=-98.91, y=103.00, z=-194.94], EntityChicken['Chicken'/283, l='MpServer', x=-106.66, y=102.00, z=-180.59], EntityZombie['Zombie'/285, l='MpServer', x=-91.59, y=44.00, z=-111.25], EntityZombie['Zombie'/286, l='MpServer', x=-99.69, y=46.00, z=-110.31], EntitySkeleton['Skeleton'/287, l='MpServer', x=-92.50, y=44.00, z=-108.50], EntitySkeleton['Skeleton'/288, l='MpServer', x=-94.50, y=44.00, z=-108.50], EntityCreeper['Creeper'/289, l='MpServer', x=-94.78, y=44.00, z=-112.31], EntityPig['Pig'/290, l='MpServer', x=-92.22, y=100.00, z=-105.38], EntityPig['Pig'/291, l='MpServer', x=-105.53, y=100.00, z=-104.03], EntitySheep['Sheep'/292, l='MpServer', x=-84.81, y=111.00, z=-107.78], EntitySkeleton['Skeleton'/293, l='MpServer', x=-103.50, y=53.00, z=-95.50], EntitySkeleton['Skeleton'/294, l='MpServer', x=-101.53, y=53.00, z=-94.09], EntityCreeper['Creeper'/295, l='MpServer', x=-97.56, y=56.00, z=-91.03], EntityBat['Bat'/296, l='MpServer', x=-100.88, y=50.10, z=-95.38], EntityCreeper['Creeper'/297, l='MpServer', x=-99.03, y=55.00, z=-89.56], EntitySkeleton['Skeleton'/298, l='MpServer', x=-101.06, y=56.00, z=-87.53], EntitySheep['Sheep'/299, l='MpServer', x=-108.19, y=92.00, z=-90.50], EntitySheep['Sheep'/300, l='MpServer', x=-104.34, y=80.00, z=-84.47], EntitySheep['Sheep'/301, l='MpServer', x=-101.94, y=98.00, z=-92.03], EntityPig['Pig'/302, l='MpServer', x=-104.03, y=96.00, z=-90.50], EntityChicken['Chicken'/303, l='MpServer', x=-204.59, y=63.00, z=-131.38], EntityPig['Pig'/304, l='MpServer', x=-210.03, y=64.00, z=-131.03], EntitySheep['Sheep'/305, l='MpServer', x=-192.19, y=64.00, z=-138.09], EntitySheep['Sheep'/306, l='MpServer', x=-206.59, y=64.00, z=-142.09], EntitySkeleton['Skeleton'/307, l='MpServer', x=-141.56, y=28.00, z=-190.84], EntityPig['Pig'/308, l='MpServer', x=-130.38, y=101.00, z=-192.19], EntityBat['Bat'/309, l='MpServer', x=-65.52, y=34.07, z=-140.51], EntitySheep['Sheep'/310, l='MpServer', x=-205.19, y=63.00, z=-113.22], EntityChicken['Chicken'/311, l='MpServer', x=-196.44, y=63.00, z=-115.53], EntityPig['Pig'/312, l='MpServer', x=-196.19, y=64.00, z=-154.88], EntityPig['Pig'/313, l='MpServer', x=-205.13, y=64.00, z=-154.34], EntityPig['Pig'/314, l='MpServer', x=-200.09, y=64.00, z=-159.91], EntityChicken['Chicken'/315, l='MpServer', x=-201.44, y=64.00, z=-155.41], EntityPig['Pig'/316, l='MpServer', x=-159.88, y=64.00, z=-202.78], EntityPig['Pig'/317, l='MpServer', x=-152.97, y=92.00, z=-193.47], EntityChicken['Chicken'/318, l='MpServer', x=-119.88, y=94.00, z=-197.94], EntitySheep['Sheep'/319, l='MpServer', x=-112.84, y=92.00, z=-198.47], EntityPig['Pig'/320, l='MpServer', x=-123.41, y=103.00, z=-193.06], EntitySheep['Sheep'/321, l='MpServer', x=-119.44, y=97.00, z=-196.97], EntitySkeleton['Skeleton'/322, l='MpServer', x=-74.88, y=27.00, z=-116.50], EntityZombie['Zombie'/324, l='MpServer', x=-79.44, y=40.00, z=-122.59], EntitySpider['Spider'/325, l='MpServer', x=-64.00, y=39.00, z=-123.28], EntitySheep['Sheep'/326, l='MpServer', x=-77.19, y=119.00, z=-115.66], EntityItem['item.name.lootbags_lootbagUncommon'/327, l='MpServer', x=-177.94, y=18.13, z=-87.88], EntitySkeleton['Skeleton'/328, l='MpServer', x=-184.50, y=14.00, z=-189.50], EntitySkeleton['Skeleton'/329, l='MpServer', x=-181.25, y=13.00, z=-188.31], EntityZombie['Zombie'/330, l='MpServer', x=-182.94, y=21.00, z=-181.50], EntityCreeper['Creeper'/331, l='MpServer', x=-191.00, y=21.00, z=-183.44], EntityBat['Bat'/332, l='MpServer', x=-154.13, y=11.05, z=-159.78], EntitySheep['Sheep'/333, l='MpServer', x=-91.84, y=104.00, z=-182.34], EntitySheep['Sheep'/334, l='MpServer', x=-92.97, y=104.00, z=-183.25], EntitySheep['Sheep'/335, l='MpServer', x=-96.81, y=103.00, z=-190.16], EntitySheep['Sheep'/336, l='MpServer', x=-83.06, y=103.00, z=-177.94], EntityPig['Pig'/337, l='MpServer', x=-84.53, y=94.00, z=-83.03], EntitySheep['Sheep'/338, l='MpServer', x=-93.97, y=99.00, z=-95.97], EntitySheep['Sheep'/339, l='MpServer', x=-203.28, y=65.00, z=-173.28], EntitySheep['Sheep'/340, l='MpServer', x=-196.94, y=64.00, z=-161.06], EntitySkeleton['Skeleton'/341, l='MpServer', x=-171.31, y=18.00, z=-192.69], EntityPig['Pig'/342, l='MpServer', x=-164.84, y=63.00, z=-203.13], EntitySheep['Sheep'/343, l='MpServer', x=-90.38, y=104.00, z=-197.75], EntitySheep['Sheep'/344, l='MpServer', x=-100.13, y=100.00, z=-201.47], EntityItem['item.item.feather'/345, l='MpServer', x=-96.25, y=103.13, z=-200.00], EntitySheep['Sheep'/346, l='MpServer', x=-105.75, y=98.00, z=-199.81], EntitySkeleton['Skeleton'/347, l='MpServer', x=-66.75, y=28.00, z=-107.72], EntityZombie['Zombie'/348, l='MpServer', x=-196.03, y=15.00, z=-87.50], EntityZombie['Zombie'/349, l='MpServer', x=-197.50, y=15.00, z=-82.50], EntityZombie['Zombie'/350, l='MpServer', x=-197.50, y=15.00, z=-85.50], EntityCreeper['Creeper'/351, l='MpServer', x=-198.50, y=22.00, z=-190.50], EntityCreeper['Creeper'/352, l='MpServer', x=-197.50, y=21.00, z=-186.50], EntityCreeper['Creeper'/353, l='MpServer', x=-200.56, y=21.00, z=-184.94], EntityBat['Bat'/354, l='MpServer', x=-202.75, y=23.10, z=-176.25], EntityCreeper['Creeper'/355, l='MpServer', x=-199.44, y=20.00, z=-185.41], EntityPig['Pig'/356, l='MpServer', x=-212.50, y=65.00, z=-186.06], EntitySheep['Sheep'/357, l='MpServer', x=-204.03, y=66.00, z=-177.03], EntityPig['Pig'/358, l='MpServer', x=-204.06, y=66.00, z=-181.97], EntityEnderman['Enderman'/359, l='MpServer', x=-191.50, y=26.00, z=-195.50], EntityZombie['Zombie'/360, l='MpServer', x=-83.47, y=25.00, z=-206.59], EntityChicken['Chicken'/361, l='MpServer', x=-96.44, y=103.00, z=-193.59], EntityChicken['Chicken'/362, l='MpServer', x=-98.47, y=100.00, z=-201.44], EntityItem['item.item.feather'/363, l='MpServer', x=-89.53, y=104.13, z=-198.84], EntitySheep['Sheep'/364, l='MpServer', x=-73.34, y=103.00, z=-176.91], EntitySheep['Sheep'/365, l='MpServer', x=-75.81, y=106.00, z=-192.50], EntitySheep['Sheep'/366, l='MpServer', x=-67.50, y=101.00, z=-90.81], EntityPig['Pig'/367, l='MpServer', x=-78.31, y=97.00, z=-86.50], EntitySheep['Sheep'/368, l='MpServer', x=-64.47, y=101.00, z=-95.66], EntityPig['Pig'/369, l='MpServer', x=-72.78, y=90.00, z=-79.06], EntitySheep['Sheep'/370, l='MpServer', x=-219.72, y=64.00, z=-124.38], EntityPig['Pig'/371, l='MpServer', x=-209.69, y=65.00, z=-159.88], EntityBat['Bat'/118, l='MpServer', x=-131.41, y=49.10, z=-74.75], EntityPig['Pig'/375, l='MpServer', x=-215.88, y=65.00, z=-164.31], EntityZombie['Zombie'/119, l='MpServer', x=-142.47, y=48.00, z=-78.06], EntityPig['Pig'/376, l='MpServer', x=-216.19, y=66.00, z=-175.41], EntityPig['Pig'/377, l='MpServer', x=-162.59, y=63.00, z=-220.75], EntityZombie['Zombie'/379, l='MpServer', x=-202.50, y=24.00, z=-207.50], EntityEnderman['Enderman'/380, l='MpServer', x=-194.50, y=24.00, z=-194.47], EntityPig['Pig'/381, l='MpServer', x=-208.88, y=67.00, z=-183.66], EntityZombie['Zombie'/382, l='MpServer', x=-191.06, y=24.00, z=-213.38], EntityCreeper['Creeper'/383, l='MpServer', x=-80.94, y=24.00, z=-210.69], EntitySkeleton['Skeleton'/387, l='MpServer', x=-61.50, y=69.00, z=-84.50], EntityPig['Pig'/135, l='MpServer', x=-90.91, y=82.00, z=-77.22], EntityBat['Bat'/396, l='MpServer', x=-201.38, y=25.00, z=-209.47], EntityChicken['Chicken'/397, l='MpServer', x=-78.47, y=76.00, z=-220.59], EntityBat['Bat'/918, l='MpServer', x=-142.06, y=27.10, z=-106.25], EntityPig['Pig'/153, l='MpServer', x=-63.50, y=87.00, z=-66.69], EntitySheep['Sheep'/223, l='MpServer', x=-128.38, y=100.00, z=-131.81], EntitySheep['Sheep'/224, l='MpServer', x=-133.97, y=101.00, z=-154.97], EntitySkeleton['Skeleton'/225, l='MpServer', x=-116.34, y=13.00, z=-133.88], EntitySpider['Spider'/226, l='MpServer', x=-125.47, y=17.00, z=-141.75], EntityCreeper['Creeper'/227, l='MpServer', x=-135.50, y=27.00, z=-116.50], EntityPig['Pig'/228, l='MpServer', x=-107.31, y=106.00, z=-151.50], EntitySheep['Sheep'/229, l='MpServer', x=-132.14, y=100.00, z=-123.05], EntityZombie['Zombie'/230, l='MpServer', x=-144.25, y=61.00, z=-171.16], EntityZombie['Zombie'/231, l='MpServer', x=-142.50, y=61.00, z=-169.50], EntityZombie['Zombie'/232, l='MpServer', x=-99.50, y=62.00, z=-137.16], EntityBat['Bat'/233, l='MpServer', x=-100.09, y=53.16, z=-122.65], EntityPig['Pig'/234, l='MpServer', x=-107.09, y=104.00, z=-133.97], EntityCreeper['Creeper'/235, l='MpServer', x=-151.50, y=14.00, z=-107.50], EntityZombie['Zombie'/236, l='MpServer', x=-152.50, y=29.00, z=-106.78], EntitySquid['Squid'/237, l='MpServer', x=-158.50, y=57.28, z=-111.50], EntitySquid['Squid'/238, l='MpServer', x=-159.50, y=56.00, z=-115.50], EntityChicken['Chicken'/239, l='MpServer', x=-169.47, y=63.00, z=-149.56], EntityChicken['Chicken'/240, l='MpServer', x=-171.63, y=63.00, z=-153.59], EntityItem['item.item.feather'/241, l='MpServer', x=-173.47, y=63.13, z=-153.63], EntityCreeper['Creeper'/242, l='MpServer', x=-146.13, y=61.00, z=-171.16], EntitySheep['Sheep'/243, l='MpServer', x=-106.50, y=107.00, z=-155.66], EntityBat['Bat'/244, l='MpServer', x=-86.05, y=44.09, z=-103.35], EntitySkeleton['Skeleton'/245, l='MpServer', x=-120.63, y=29.00, z=-111.84], EntitySquid['Squid'/246, l='MpServer', x=-163.28, y=56.38, z=-109.03], EntitySquid['Squid'/247, l='MpServer', x=-159.50, y=57.00, z=-104.34], EntitySquid['Squid'/248, l='MpServer', x=-161.50, y=56.19, z=-105.09], EntitySquid['Squid'/249, l='MpServer', x=-164.38, y=57.78, z=-107.75], EntityZombie['Zombie'/250, l='MpServer', x=-164.50, y=19.00, z=-172.50], EntityBat['Bat'/251, l='MpServer', x=-156.41, y=20.03, z=-178.83], EntityZombie['Zombie'/252, l='MpServer', x=-165.50, y=49.00, z=-161.94], EntityCreeper['Creeper'/253, l='MpServer', x=-98.50, y=31.00, z=-165.50], EntitySkeleton['Skeleton'/254, l='MpServer', x=-104.09, y=48.00, z=-113.50], EntitySkeleton['Skeleton'/255, l='MpServer', x=-90.91, y=45.00, z=-112.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 557951248 bytes (532 MB) / 2042261504 bytes (1947 MB) up to 3113877504 bytes (2969 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 68 mods loaded, 67 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   ChickenShed{1.1.3} [Chicken Shed]([1.7.2] ChickenShed %28v1.1.3%29.jar) 
    UCHIJAAAA   AgriCraft{1.7.10-1.3.1} [AgriCraft](AgriCraft-1.7.10-1.3.1.jar) 
    UCHIJAAAA   antiqueatlas{4.2.2-1.7.10} [Antique Atlas](antiqueatlas-4.2.2-1.7.10.jar) 
    UCHIJAAAA   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJAAAA   AutoSapling{1.0} [AutoSapling](AutoSapling-1.1.jar) 
    UCHIJAAAA   BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1396-universal.jar) 
    UCHIJAAAA   BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHIJAAAA   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJAAAA   BiomeTweaker{1.2.128} [BiomeTweaker](BiomeTweaker-1.7.10-1.2.128.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJAAAA   Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.344} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UCHIJAAAA   chisel{2.3.10.37} [Chisel 2](Chisel2-2.3.10.37.jar) 
    UCHIJAAAA   Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
    UCHIJAAAA   chiseltones{@VERSION@} [Chisel Tones](ChiselTones-1.7.10-1.0-1.jar) 
    UCHIJAAAA   compactstorage{v2.0.0a} [CompactStorage](compactstorage-1.7.10-release-2.0.0.9-universal.jar) 
    UCHIJAAAA   D3Core{1.1.1.39} [D3Core](D3Core-1.7.10-1.1.1.39.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   endercompass{1.1} [Ender Compass](EnderCompass-1.7.10-1.1.jar) 
    UCHIJAAAA   extrabuttons{1.7.10.1} [ExtraButtons](ExtraButtons-1.7.10.1.jar) 
    UCHIJAAAA   fastleafdecay{1.0} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.0.jar) 
    UCHIJAAAA   FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UCHIJAAAA   HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) 
    UCHIJAAAA   inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   jacb{1.0.2} [JACB](JACB-1.7.10-1.0.2.jar) 
    UCHIJAAAA   journeymap{5.1.4p1} [JourneyMap](journeymap-1.7.10-5.1.4p1-unlimited.jar) 
    UCHIJAAAA   LLadders{0.5.0} [Luppii's Ladders](Ladders-0.5.0-MC1.7.10.jar) 
    UCHIJAAAA   LavaBoat{2.0.0} [LavaBoat](LavaBoat 2.0.0.jar) 
    UCHIJAAAA   lootbags{2.0.8} [Loot Bags](LootBags-1.7.10-2.0.8.jar) 
    UCHIJAAAA   MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJAAAA   Morpheus{1.7.10-1.6.4} [Morpheus](Morpheus-1.7.10-1.6.4.jar) 
    UCHIJAAAA   NEIAddons{1.12.9.32} [NEI Addons](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo](neiaddons-1.12.9.32-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCHIJAAAA   bonecraft{1.7.2b} [Pam's BoneCraft](Pam's BoneCraft 1.7.2b.zip) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJAAAA   mobdropcrops{1.7.2a} [Pam's Mob Drop Crops](Pam's Mob Drop Crops 1.7.10a.zip) 
    UCHIJAAAA   weeeflowers{1.7.2b} [Pam's Weee! Flowers](Pam's WeeeFlowers 1.7.2b.zip) 
    UCHIJAAAA   ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHIJAAAA   ResourceLoader{1.2} [Resource Loader](ResourceLoader-1.2.jar) 
    UCHIJAAAA   SpiceOfLife{1.2.3} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.3.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.5.5} [Storage Drawers](StorageDrawers-1.7.10-1.5.5.jar) 
    UCHIJAAAA   supercraftingframe{1.7.10.3} [Super Crafting Frame](supercraftingframe-1.7.10.3.jar) 
    UCHIJAAAA   ttCore{MC1.7.10-0.1.0-67} [ttCore](ttCore-MC1.7.10-0.1.0-67.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHIJAAAA   wawla{1.3.1} [What Are We Looking At](Wawla-1.0.5.120.jar) 
    UCHIJAAAA   McMultipart{1.2.0.344} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.0.8.16} [MrTJPCore](MrTJPCore-1.0.8.16-universal.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.344} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UD  BiomeTweakerCore{1.2.128} [BiomeTweaker Core](minecraft.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.0' Renderer: 'AMD Radeon HD 7700 Series'
    Mantle Environment: Environment healthy.
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7700 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Better than Default 1.7.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Ashakiwi** [comment]
If I missed a tutorial for adding the updated presser recipe from #94 then I would happily follow it if I could find one. I tried opening the jar and inserting the code from that solution. :(
