### ISSUE TITLE
Fluid dump not working

### ISSUE THREAD

**Issue by andybish** [Tonius/NEI-Integration#109]
I'm running a custom modpack with a lot of mods. Trying to dump fluid ids, I click the button, but all it does is generate an empty fluid.csv file in the dumps folder. Other dumps all appear to work fine. This error appears in console:

```
[19:22:04] [Client thread/ERROR] [NotEnoughItems]: Error dumping Fluids mode: 0
java.lang.NullPointerException
at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:204) ~[FluidRegistry.class:?]
at net.minecraftforge.fluids.Fluid.getID(Fluid.java:174) ~[Fluid.class:?]
at tonius.neiintegration.mods.mcforge.dumpers.FluidDumper$1.compare(FluidDumper.java:35) ~[FluidDumper$1.class:?]
at tonius.neiintegration.mods.mcforge.dumpers.FluidDumper$1.compare(FluidDumper.java:32) ~[FluidDumper$1.class:?]
at java.util.TimSort.binarySort(TimSort.java:296) ~[?:1.8.0_92]
at java.util.TimSort.sort(TimSort.java:239) ~[?:1.8.0_92]
at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_92]
at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_92]
at java.util.Collections.sort(Collections.java:175) ~[?:1.8.0_92]
at tonius.neiintegration.mods.mcforge.dumpers.FluidDumper.dump(FluidDumper.java:32) ~[FluidDumper.class:?]
at codechicken.nei.config.DataDumper.dumpTo(DataDumper.java:66) ~[DataDumper.class:?]
at codechicken.nei.config.DataDumper.dumpFile(DataDumper.java:41) [DataDumper.class:?]
at codechicken.nei.config.DataDumper.mouseClicked(DataDumper.java:141) [DataDumper.class:?]
at codechicken.nei.config.GuiOptionList$OptionScrollSlot.slotClicked(GuiOptionList.java:129) [GuiOptionList$OptionScrollSlot.class:?]
at codechicken.core.gui.GuiScrollSlot.slotUp(GuiScrollSlot.java:129) [GuiScrollSlot.class:?]
at codechicken.core.gui.GuiScrollPane.mouseMovedOrUp(GuiScrollPane.java:143) [GuiScrollPane.class:?]
at codechicken.core.gui.GuiScreenWidget.func_146286_b(GuiScreenWidget.java:96) [GuiScreenWidget.class:?]
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) [bdw.class:?]
at codechicken.core.gui.GuiScreenWidget.func_146274_d(GuiScreenWidget.java:127) [GuiScreenWidget.class:?]
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by rhoark** [comment]
I'm seeing this too. Looks like FluidDumper.java needs to check for null before doing the comparison on line 35.
