### ISSUE TITLE
Crash with Latest OC build.

### ISSUE THREAD

**Issue by scj643** [Tonius/NEI-Integration#30]
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/10/14 2:53 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.util.StatCollector.translateToLocal(Ljava/lang/String;)Ljava/lang/String;
	at tonius.neiintegration.Utils.translate(Utils.java:22)
	at tonius.neiintegration.Utils.translate(Utils.java:26)
	at tonius.neiintegration.forge.RecipeHandlerFluidRegistry.getRecipeName(RecipeHandlerFluidRegistry.java:124)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:19)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tonius.neiintegration.Utils.translate(Utils.java:22)
	at tonius.neiintegration.Utils.translate(Utils.java:26)
	at tonius.neiintegration.forge.RecipeHandlerFluidRegistry.getRecipeName(RecipeHandlerFluidRegistry.java:124)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:19)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['scj643'/388, l='MpServer', x=167.16, y=70.62, z=246.38]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (164,64,248), Chunk: (at 4,4,8 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2215 game time, 2215 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityPig['Pig'/274, l='MpServer', x=225.50, y=63.00, z=315.50], EntitySkeleton['Skeleton'/272, l='MpServer', x=225.50, y=40.00, z=258.50], EntityZombie['Zombie'/263, l='MpServer', x=230.66, y=24.00, z=231.50], EntityBat['Bat'/261, l='MpServer', x=238.25, y=35.10, z=225.75], EntitySkeleton['Skeleton'/264, l='MpServer', x=231.06, y=26.00, z=239.44], EntityBat['Bat'/1344, l='MpServer', x=149.26, y=14.90, z=279.96], EntityZombie['Zombie'/268, l='MpServer', x=231.34, y=24.00, z=243.34], EntityBat['Bat'/1345, l='MpServer', x=154.54, y=15.27, z=280.48], EntityBat['Bat'/1135, l='MpServer', x=212.60, y=23.00, z=207.94], EntitySkeleton['Skeleton'/1603, l='MpServer', x=197.50, y=15.00, z=305.50], EntityZombie['Zombie'/1625, l='MpServer', x=229.50, y=49.00, z=249.50], EntityZombie['Zombie'/1624, l='MpServer', x=227.50, y=49.00, z=252.50], EntityPig['Pig'/290, l='MpServer', x=233.06, y=76.00, z=200.88], EntityCreeper['Creeper'/1621, l='MpServer', x=106.50, y=18.00, z=191.50], EntitySpider['Spider'/1620, l='MpServer', x=110.50, y=18.00, z=193.50], EntityZombie['Zombie'/1623, l='MpServer', x=228.50, y=49.00, z=251.50], EntityBat['Bat'/69, l='MpServer', x=124.40, y=38.14, z=218.91], EntitySpider['Spider'/1310, l='MpServer', x=221.13, y=17.00, z=189.75], EntityCreeper['Creeper'/1576, l='MpServer', x=204.50, y=34.00, z=279.50], EntitySkeleton['Skeleton'/1308, l='MpServer', x=222.69, y=17.00, z=188.31], EntityCreeper['Creeper'/1575, l='MpServer', x=204.50, y=34.00, z=278.50], EntityCreeper['Creeper'/1846, l='MpServer', x=201.50, y=18.00, z=190.50], EntitySkeleton['Skeleton'/79, l='MpServer', x=101.09, y=17.00, z=246.44], EntitySkeleton['Skeleton'/1291, l='MpServer', x=152.50, y=14.00, z=272.50], EntitySpider['Spider'/1293, l='MpServer', x=145.72, y=15.00, z=279.28], EntityZombie['Zombie'/95, l='MpServer', x=111.50, y=39.00, z=237.50], EntitySkeleton['Skeleton'/94, l='MpServer', x=106.50, y=17.00, z=239.50], EntitySpider['Spider'/88, l='MpServer', x=107.72, y=19.00, z=194.28], EntitySpider['Spider'/91, l='MpServer', x=103.00, y=46.00, z=208.22], EntitySkeleton['Skeleton'/90, l='MpServer', x=99.50, y=38.00, z=192.50], EntitySkeleton['Skeleton'/98, l='MpServer', x=110.84, y=15.00, z=278.50], EntitySkeleton['Skeleton'/96, l='MpServer', x=108.50, y=17.00, z=240.50], EntityBat['Bat'/108, l='MpServer', x=109.25, y=37.10, z=195.25], EntityItem['item.tile.mushroom'/109, l='MpServer', x=126.53, y=24.13, z=234.53], EntitySkeleton['Skeleton'/114, l='MpServer', x=114.63, y=16.00, z=280.31], EntityItem['item.item.seeds'/1317, l='MpServer', x=184.84, y=62.13, z=265.50], EntityClientPlayerMP['scj643'/388, l='MpServer', x=167.16, y=70.62, z=246.38], EntitySkeleton['Skeleton'/154, l='MpServer', x=127.97, y=12.00, z=253.50], EntityBat['Bat'/144, l='MpServer', x=143.25, y=34.00, z=214.56], EntityZombie['Zombie'/147, l='MpServer', x=137.50, y=40.00, z=215.50], EntityItem['item.tile.mushroom'/150, l='MpServer', x=128.88, y=25.13, z=236.13], EntitySkeleton['Skeleton'/1255, l='MpServer', x=235.50, y=24.00, z=204.50], EntityChicken['Chicken'/171, l='MpServer', x=134.56, y=65.00, z=241.44], EntityChicken['Chicken'/173, l='MpServer', x=167.44, y=68.00, z=239.53], EntityChicken['Chicken'/172, l='MpServer', x=139.56, y=65.00, z=236.56], EntityCreeper['Creeper'/1748, l='MpServer', x=228.50, y=33.00, z=228.50], EntityCreeper['Creeper'/1750, l='MpServer', x=107.50, y=47.00, z=203.50], EntityCreeper['Creeper'/1265, l='MpServer', x=123.50, y=38.00, z=213.50], EntitySkeleton['Skeleton'/182, l='MpServer', x=164.09, y=58.00, z=309.47], EntityChicken['Chicken'/181, l='MpServer', x=149.72, y=65.00, z=250.63], EntityPig['Pig'/201, l='MpServer', x=181.81, y=69.00, z=256.13], EntitySkeleton['Skeleton'/1156, l='MpServer', x=-4.16, y=-19.62, z=-42.38], EntityPig['Pig'/200, l='MpServer', x=168.94, y=67.00, z=269.06], EntityPig['Pig'/202, l='MpServer', x=197.94, y=69.00, z=240.75], EntityPig['Pig'/197, l='MpServer', x=167.50, y=66.00, z=279.81], EntityZombie['Zombie'/196, l='MpServer', x=177.50, y=19.00, z=258.50], EntityPig['Pig'/199, l='MpServer', x=185.31, y=65.00, z=262.53], EntityPig['Pig'/198, l='MpServer', x=188.66, y=65.00, z=258.47], EntityPig['Pig'/193, l='MpServer', x=173.94, y=70.00, z=244.94], EntityItem['item.item.seeds'/192, l='MpServer', x=190.56, y=63.13, z=213.13], EntityZombie['Zombie'/194, l='MpServer', x=187.50, y=12.00, z=270.50], EntitySkeleton['Skeleton'/1718, l='MpServer', x=192.72, y=13.00, z=316.75], EntityPig['Pig'/220, l='MpServer', x=202.50, y=66.00, z=192.50], EntitySkeleton['Skeleton'/1719, l='MpServer', x=194.66, y=13.00, z=317.34], EntityItem['item.tile.mushroom'/222, l='MpServer', x=199.47, y=40.13, z=223.81], EntityItem['item.tile.mushroom'/223, l='MpServer', x=195.13, y=40.13, z=226.81], EntityPig['Pig'/216, l='MpServer', x=200.50, y=66.00, z=189.50], EntityEnderman['Enderman'/217, l='MpServer', x=204.28, y=17.00, z=194.50], EntityPig['Pig'/218, l='MpServer', x=191.03, y=65.00, z=200.16], EntityPig['Pig'/219, l='MpServer', x=192.25, y=65.00, z=199.19], EntitySkeleton['Skeleton'/1720, l='MpServer', x=191.50, y=13.00, z=315.50], EntitySkeleton['Skeleton'/1721, l='MpServer', x=193.50, y=13.00, z=315.50], EntityBat['Bat'/1671, l='MpServer', x=98.45, y=16.93, z=174.34], EntityCreeper['Creeper'/1460, l='MpServer', x=128.50, y=44.00, z=206.50], EntitySkeleton['Skeleton'/1461, l='MpServer', x=121.50, y=44.00, z=207.50], EntityPig['Pig'/229, l='MpServer', x=204.50, y=66.00, z=273.50], EntityPig['Pig'/228, l='MpServer', x=207.16, y=68.00, z=274.03], EntityPig['Pig'/227, l='MpServer', x=203.50, y=64.00, z=279.50], EntityBat['Bat'/1672, l='MpServer', x=95.24, y=16.80, z=179.90], EntityPig['Pig'/226, l='MpServer', x=204.50, y=66.00, z=270.50], EntityItem['item.tile.mushroom'/225, l='MpServer', x=196.81, y=40.13, z=224.84], EntityItem['item.tile.mushroom'/224, l='MpServer', x=196.53, y=40.13, z=225.81], EntityBat['Bat'/1684, l='MpServer', x=239.35, y=22.61, z=310.89], EntityBat['Bat'/1685, l='MpServer', x=227.70, y=20.53, z=317.39], EntityCow['Cow'/250, l='MpServer', x=211.50, y=70.00, z=271.50], EntityBat['Bat'/1681, l='MpServer', x=229.45, y=23.74, z=322.67], EntityPig['Pig'/251, l='MpServer', x=223.50, y=63.00, z=314.50], EntityBat['Bat'/1682, l='MpServer', x=230.51, y=19.48, z=305.94], EntityCow['Cow'/248, l='MpServer', x=213.50, y=70.00, z=267.50], EntityCow['Cow'/249, l='MpServer', x=210.50, y=70.00, z=266.50], EntityPig['Pig'/246, l='MpServer', x=216.97, y=71.00, z=251.81], EntityCow['Cow'/247, l='MpServer', x=211.50, y=70.00, z=269.50], EntityPig['Pig'/244, l='MpServer', x=223.06, y=72.00, z=255.97], EntityZombie['Zombie'/1450, l='MpServer', x=98.50, y=21.00, z=251.50], EntityPig['Pig'/245, l='MpServer', x=217.63, y=71.00, z=253.25], EntitySkeleton['Skeleton'/1214, l='MpServer', x=145.50, y=40.00, z=216.50], EntitySkeleton['Skeleton'/1215, l='MpServer', x=146.50, y=40.00, z=215.50], EntityPig['Pig'/243, l='MpServer', x=206.22, y=70.00, z=251.41], EntityPig['Pig'/240, l='MpServer', x=204.06, y=66.00, z=177.16], EntitySkeleton['Skeleton'/241, l='MpServer', x=211.88, y=19.00, z=198.34]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298285504 bytes (284 MB) / 1026031616 bytes (978 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1258 Minecraft Forge 10.13.2.1258 16 mods loaded, 16 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1258} [Forge Mod Loader] (forge-1.7.10-10.13.2.1258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1258} [Minecraft Forge] (forge-1.7.10-10.13.2.1258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.73} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	neiintegration{1.0.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.5.8.59} [ProjectRed] (ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenComputers{1.4.2.274-dev} [OpenComputers] (OpenComputers-MC1.7.10-1.4.2.274-dev-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.5.8.59} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1258
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.3347, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by Tonius** [comment]
I have still yet to see this crash myself, and the bug hasn't been reported to me since. Closing.
