### ISSUE TITLE
Failed to load Config ?

### ISSUE THREAD

**Issue by SebiOo** [Tonius/NEI-Integration#45]
Everything looks normal but as soon as i join a server i get:

[Client thread/ERROR] [NotEnoughItems]: Failed to Load tonius.neiintegration.NEIIntegrationConfig
java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:119) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.Fluid.getID(Fluid.java:177) ~[Fluid.class:?]
	at tonius.neiintegration.forge.RecipeHandlerFluidRegistry$1.compare(RecipeHandlerFluidRegistry.java:40) ~[RecipeHandlerFluidRegistry$1.class:?]
	at tonius.neiintegration.forge.RecipeHandlerFluidRegistry$1.compare(RecipeHandlerFluidRegistry.java:36) ~[RecipeHandlerFluidRegistry$1.class:?]
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source) ~[?:1.7.0_72]
	at java.util.TimSort.sort(Unknown Source) ~[?:1.7.0_72]
	at java.util.TimSort.sort(Unknown Source) ~[?:1.7.0_72]
	at java.util.Arrays.sort(Unknown Source) ~[?:1.7.0_72]
	at java.util.Collections.sort(Unknown Source) ~[?:1.7.0_72]
	at tonius.neiintegration.forge.RecipeHandlerFluidRegistry.prepare(RecipeHandlerFluidRegistry.java:36) ~[RecipeHandlerFluidRegistry.class:?]
	at tonius.neiintegration.IntegrationBase.registerHandler(IntegrationBase.java:14) ~[IntegrationBase.class:?]
	at tonius.neiintegration.forge.ForgeIntegration.loadConfig(ForgeIntegration.java:27) ~[ForgeIntegration.class:?]
	at tonius.neiintegration.NEIIntegrationConfig.loadConfig(NEIIntegrationConfig.java:12) ~[NEIIntegrationConfig.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:278) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by SebiOo** [comment]
Using the direwolf20 pack (1.0.3)
Modlist here : https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3

**Comment by iTitus** [comment]
There is a null-fluid in the FluidRegistry.
More null-checks :P

**Comment by Tonius** [comment]
Really? Mods are registering null Fluids now?

**Comment by iTitus** [comment]
Nah, I derped. The List in the FluidRegistry is somehow null.

**Comment by iTitus** [comment]
This is very strange.
