### ISSUE TITLE
Rolling Machine recipes no longer showing with version 1.0.13

### ISSUE THREAD

**Issue by Tedyhere** [Tonius/NEI-Integration#98]
Title says it all, no rolling machine recipes are showing up with version 1.0.13 in NEI

**Comment by Tonius** [comment]
What version of Railcraft are you using? Do any errors show up in the log when trying to look up items made with the Rolling Machine?

**Comment by Tedyhere** [comment]
RC 9.8.0.0 and I think I see an issue that I did not notice before. 
Failed to scan C:\Users\Alan\Documents\Curse\Minecraft\Install\versions\forge-10.13.4.1566\forge-10.13.4.1566.jar, the zip file is invalid
java.util.zip.ZipException: invalid entry size (expected 67324752 but got 2231 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384) ~[?:1.8.0_25]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[?:1.8.0_25]
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140) ~[?:1.8.0_25]
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118) ~[?:1.8.0_25]
	at codechicken.core.ClassDiscoverer.readFromZipFile(ClassDiscoverer.java:116) ~[ClassDiscoverer.class:?]
	at codechicken.core.ClassDiscoverer.findClasspathMods(ClassDiscoverer.java:100) [ClassDiscoverer.class:?]
	at codechicken.core.ClassDiscoverer.findClasses(ClassDiscoverer.java:51) [ClassDiscoverer.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:273) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

and 

[17:23:11] [Client thread/ERROR] [NotEnoughItems/]: Failed to Load tonius.neiintegration.NEIConfig
java.lang.NullPointerException
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258) ~[?:1.8.0_25]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203) ~[?:1.8.0_25]
	at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_25]
	at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_25]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_25]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_25]
	at tonius.neiintegration.mods.mcforge.RecipeHandlerOreDictionary.prepare(RecipeHandlerOreDictionary.java:27) ~[RecipeHandlerOreDictionary.class:?]
	at tonius.neiintegration.IntegrationBase.registerHandler(IntegrationBase.java:18) ~[IntegrationBase.class:?]
	at tonius.neiintegration.mods.mcforge.MCForgeIntegration.loadConfig(MCForgeIntegration.java:26) ~[MCForgeIntegration.class:?]
	at tonius.neiintegration.NEIConfig.loadConfig(NEIConfig.java:12) ~[NEIConfig.class:?]
	at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:278) [NEIClientConfig.class:?]
	at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
	at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
	at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) [PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) [PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) [PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
